### ISSUE TITLE
Error with an empty caption

### ISSUE THREAD

**Issue by asdor** [igsha/instafs#1]
If the page contains photo without caption, then instafs fails.
Example:
```
$ instafs -u abcde /tmp/mnt
Traceback (most recent call last):
  File "/nix/store/9j293nx3whssh9j05ql4l20q9jyqzdq2-instafs-0.0.1/bin/.instafs-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/9j293nx3whssh9j05ql4l20q9jyqzdq2-instafs-0.0.1/lib/python3.7/site-packages/instafs/instafs.py", line 50, in main
    server = InstaFS(args.user)
  File "/nix/store/9j293nx3whssh9j05ql4l20q9jyqzdq2-instafs-0.0.1/lib/python3.7/site-packages/instafs/instafs.py", line 12, in __init__
    self.tree = tree.Tree(username)
  File "/nix/store/9j293nx3whssh9j05ql4l20q9jyqzdq2-instafs-0.0.1/lib/python3.7/site-packages/instafs/tree.py", line 55, in __init__
    self.profile = instagram.Profile(username)
  File "/nix/store/9j293nx3whssh9j05ql4l20q9jyqzdq2-instafs-0.0.1/lib/python3.7/site-packages/instafs/instagram.py", line 115, in __init__
    self.posts = [Post(edge, self.count - idx) for idx, edge in enumerate(media['edges'])]
  File "/nix/store/9j293nx3whssh9j05ql4l20q9jyqzdq2-instafs-0.0.1/lib/python3.7/site-packages/instafs/instagram.py", line 115, in <listcomp>
    self.posts = [Post(edge, self.count - idx) for idx, edge in enumerate(media['edges'])]
  File "/nix/store/9j293nx3whssh9j05ql4l20q9jyqzdq2-instafs-0.0.1/lib/python3.7/site-packages/instafs/instagram.py", line 87, in __init__
    self.caption = toutf8(node['edge_media_to_caption']['edges'][0]['node']['text'])
IndexError: list index out of range
```

**Comment by igsha** [comment]
Thanks for the example!
